/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kopikuy;

/**
 *
 * @author FASIH
 */
import com.sun.java.swing.plaf.windows.resources.windows;
import config.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
    private koneksi db = new koneksi();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        version.setText(UserSession.GetVersion());
        combobox_level();
        combobox_shift();
        
    }
    
    public void combobox_level(){
      
        try {
            String query = "SELECT * FROM level";
            Statement st = db.koneksidb().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {                
                level.addItem(rs.getString("name"));
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "DAtabase gagal terhubung"+e);
        }
    }
    
    public void combobox_shift(){
      
        try {
            String query = "SELECT * FROM shift";
            Statement st = db.koneksidb().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {                
                cmb_shift.addItem(rs.getString("name"));
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "DAtabase gagal terhubung"+e);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        version = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        cmb_shift = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 42));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1095, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(version, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 44.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        username.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        username.setBorder(null);
        username.setOpaque(false);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 250, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 46.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 47.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 45.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        level.setBackground(new java.awt.Color(185, 201, 231));
        level.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        level.setToolTipText("");
        level.setAlignmentX(10.0F);
        level.setAlignmentY(10.0F);
        level.setBorder(null);
        level.setPreferredSize(new java.awt.Dimension(223, 48));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        jPanel2.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 280, 40));

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 51.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        password.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        password.setToolTipText("");
        password.setBorder(null);
        password.setOpaque(false);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 46.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 52.png"))); // NOI18N
        btnlogin.setBorder(null);
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlogin.setFocusPainted(false);
        btnlogin.setOpaque(false);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 130, 43));

        cmb_shift.setBackground(new java.awt.Color(185, 201, 231));
        cmb_shift.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        cmb_shift.setToolTipText("");
        cmb_shift.setAlignmentX(10.0F);
        cmb_shift.setAlignmentY(10.0F);
        cmb_shift.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmb_shift.setPreferredSize(new java.awt.Dimension(223, 48));
        cmb_shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_shiftActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 280, 40));

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 50.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 43.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 460, 570));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 42.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login/Asset 74.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
       
    }//GEN-LAST:event_levelActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String username = this.username.getText();
        String password = this.password.getText();
        String level = this.level.getSelectedItem().toString();
        String shift = this.cmb_shift.getSelectedItem().toString();
        
        try {      
            String query = "SELECT *, karyawan.name as nama_karyawan, shift.name as nama_shift, level.name as nama_level \n" +
                            "FROM users \n" +
                            "JOIN shift_karyawan ON users.karyawanID=shift_karyawan.karyawanID \n" +
                            "JOIN karyawan ON karyawan.karyawanID=shift_karyawan.karyawanID \n" +
                            "JOIN shift ON shift.shiftID=shift_karyawan.shiftID \n" +
                            "JOIN level ON users.levelID=level.levelID \n" +
                            "WHERE users.username='"+username+"' && users.password='"+password+"' && shift.name='"+shift+"'";
            Statement st = db.koneksidb().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if (rs.next()) {
                if (username.equals(rs.getString("username")) && password.equals(rs.getString("password"))) {
                    if (rs.getString("nama_level").equals(level)) {
                        if (rs.getString("nama_shift").equals(shift)) {
                            UserSession.setUserLogin(level);
                            UserSession.setKaryawanLogin(rs.getString("nama_karyawan"));
                            Dashboard ds = new Dashboard();
                            ds.setVisible(true);
                            ds.pack();
                            ds.setLocationRelativeTo(null);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "anda salah shift");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "role tidak cocok");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Akun tidak ditemukan atau Shift anda salah");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database gagal "+e);
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void cmb_shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_shiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_shiftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> cmb_shift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
